### ISSUE TITLE
Tic Tac Toe

### ISSUE THREAD

**Issue by caalberts** [caalberts/wdi-sg-playground#2]
https://github.com/caalberts/wdi-sg-playground/tree/master/tictactoe

**Comment by cbas** [comment]
*Didn't get the notification because of the typo in my name in the issue description. Also, you pinged some random person. :flushed:*

Reviewed version: https://github.com/caalberts/wdi-sg-playground/blob/0fecf03e953337fe69c64462f1dbfe03d1642b15/tictactoe/game.js

### NodeList to Array conversion
> ```js
> var tiles = Array.prototype.slice.call(document.querySelectorAll('.tile'))
> ```

Smells:
- This code is not really doing what it says it does (slicing any arrays)

Refactor to:
- Use `Array.from()` instead of the `[].slice` hack. Slightly more readable. Or with DOM4, and a polyfill, use `document.queryAll` which returns an array of `Element` instances.

### Ternary shorthand
> ```js
> player ? tile.textContent = 'X' : tile.textContent = 'O'
>

Smells:
- Repeated `tile.textContent =`
- Ternary statement return value is not used.

Refactor to:
```js
tile.textContent = player ? 'X' : 'O'
```

### Nested `if`/`else`
> ```js
> if (winner) {
>   // ...
> } else {
>   if (moves === 9) {
>     // ...
>   } else {
>     // ...
>   }
> }
> ```

Smells:
- Awkward nesting

Refactor to:

```js
if (winner) {
  // ...
} else if (moves === 9) {
  // ...
} else {
 // ...
}
```

### Side effects
> ```js
> function changePlayer () {
>   player = !player
>   updateTitle()
> }
> ```

Smell:
- A function called `changePlayer` is not expected to also go and modify the DOM. In a small app like this it is negligible but in larger apps I wouldn't be able to remember all the idiosyncrasies of the many little functions with side effects.

Refactor to:
```js
// Make the function do just what it says, no more.
function changePlayer () {
  player = !player
}
// and then elsewhere ...
changePlayer()
updateTitle()
```
In a more complex app I would imagine that changing the player triggers a custom event that is listened for by the title, which updates itself upon a changed player.

### Functional Programming
> ```js
>   var winningCombination = [ [0, 1, 2], [3, 4, 5], [6, 7, 8],
>                              [0, 3, 6], [1, 4, 7], [2, 5, 8],
>                              [0, 4, 8], [2, 4, 6]]
>   winningCombination.forEach(function (combo) {
>     if (!winner) {
>       winner = checkTiles(tiles[combo[0]], tiles[combo[1]], tiles[combo[2]])
>     }
>   })
> ```

Smells:
- Side effect from the iterator function: Mutates the global `winner` variable.
- Duplication of the `tiles[combo[...]]` code.

Refactor to:
```js
winner = winningCombination
  .some(combo => combo
    .map(index => tiles[combo[index]])
    .every(tile => tile.textContent === player ? 'X' : 'O')
  )
```
(Did not test this code so I hope/doubt it works. :grin:)

### Fat Arrow Functions
> ```js
>   tiles.forEach(function (tile) {
>     tile.textContent = ''
>   })
> ```

Smells:
- Quite a lot of code for a simple thing.

Refactor to:
```js
tiles.forEach(tile => tile.textContent = '')
```

**Comment by caalberts** [comment]
@cbas thanks. I updated the code except for the "Functional programming" part. Still trying to understand what it does.

**Comment by caalberts** [comment]
This is the code I did to refactor the findWinner() function:
```
if (winningCombination.some(combo => combo.every(tileIndex => tiles[tileIndex].textContent === 'X'))) {
    return 'X'
} else if (winningCombination.some(combo => combo.every(tileIndex => tiles[tileIndex].textContent === 'O'))) {
    return 'O'
}
```

**Comment by cbas** [comment]
Nice! You can even avoid the duplication by checking only for the current player. It's unlikely that the other player would win on a turn that is not theirs. :grimacing:
